
version: '3.8'
services:
  web:
    image: python:3.13-alpine
    build:
      context: "https://github.com/GroveLive/CasaBella.git"
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=F2lCLAg76EfRwbd1mkTnC2ZdEuwp8teHyADb7n23YomSk2VI4CipeyW21XZLApIe
      - POSTGRES_DB=CasaBella
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
