
version: '3.8'
services:
  web:
    image: python:3.13-alpine
    build:
      context: "https://github.com/GroveLive/CasaBella.git"
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]
